apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pod
  template:
    metadata:
      labels:
        name: pod
    spec:
      serviceAccountName: pod
      containers:
        - name: pod
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - pod
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "pod"
