kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods
subjects:
  - kind: ServiceAccount
    name: pod
    namespace: default
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: pod
  apiGroup: rbac.authorization.k8s.io
